blank_issues_enabled: false

contact_links:
  - name: Uinex
    url: https://github.com/djoezeke/uinex
    about: Modern GUIs with pygame.

  - name: Uinex Issues | Bug Bounty
    url: https://github.com/djoezeke/uinex/issues
    about: Please report issues and vulnerabilities here.

  - name: Uinex Releases
    url: https://github.com/djoezeke/uinex/releases
    about: Please latest Uinex release here.
