blank_issues_enabled: false

contact_links:
  - name: Uinex Engine ğŸ®
    url: https://github.com/djoezeke/uinex
    about: Modern Pygame Gui with Python.

  - name: Uinex Discussions ğŸ’–
    url: https://github.com/djoezeke/uinex/discussions
    about: The "Discussions" forum is where you want to start.

  - name: Uinex Issues | Bug Bounty ğŸ
    url: https://github.com/djoezeke/uinex/issues
    about: Please report issues and vulnerabilities here.

  - name: Uinex Releases
    url: https://github.com/djoezeke/uinex/releases
    about: Please latest Uinex release here.
